export enum ScreenNames {
  LOGIN_PAGE = 'LOGIN_PAGE',
  REGISTRATION_PAGE = 'REGISTRATION_PAGE',
  HOME_PAGE = 'HOME_PAGE',
  LOGGED_IN_STACK = 'LOGGED_IN_STACK',
  LOGGED_OUT_STACK = 'LOGGED_OUT_STACK',
}
